// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalDashboard.V2.Platform;

#nullable disable

namespace PersonalDashboard.V2.Host.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    partial class PlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalDashboard.V2.Platform.Persistence.EntityChangeCursorRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("entity_change_cursor", "platform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Sequence = 0L
                        });
                });

            modelBuilder.Entity("PersonalDashboard.V2.Platform.Persistence.EntityChangeRow", b =>
                {
                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Sequence");

                    b.HasIndex("Type", "Id", "Version");

                    b.ToTable("entity_change_journal", "platform");
                });

            modelBuilder.Entity("PersonalDashboard.V2.Platform.Persistence.SyncOperationResultRow", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("OperationId");

                    b.ToTable("sync_operation_results", "platform");
                });
#pragma warning restore 612, 618
        }
    }
}
